### ISSUE TITLE
Galaxy and ImageJ - still alive?

### ISSUE THREAD

**Issue by bgruening** [mutterer/ij-galaxy#1]
Hi,

is this project still alive? If so it would be interesting to join forces as we also did some work in this direction: https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/imagej2

Ciao,
Bjoern

**Comment by mutterer** [comment]
That is great, thanks a lot for sharing.
TBH for my project, I decided against providing all ops as Galaxy tools, as I find test iterations to be painful when workflows are developped in Galaxy. This is why for the only functional project I have using this, the workflow is provided as a single tool wrapping a Fiji macro.
I'll link your project in my readme file, as it definitely is more advanced.
Best regards,
Jerome.

**Comment by bgruening** [comment]
Thanks Jerome, that is good to know!
